# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redistr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisub',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
